<a href="https://colab.research.google.com/github/sarthak0806/oibsip_1/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline


Dataset

In [ ]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.describe()

Visualisation


In [ ]:

sns.pairplot(df,hue='Species')

Seperate feature and target(slicing of matrix)

In [ ]:
data = df.values
X = data[:,1:5]
Y = data[:,5]
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Splitting the data into training and testing for further model development

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)
print(X_test)

Logistic Regression

In [ ]:
#logistic Regression
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)

LogisticRegression()

In [ ]:
prediction = model_LR.predict(X_test)
from sklearn.metrics import accuracy_score
accu = int(accuracy_score(y_test,prediction)*100)
print(f"Our model accuracy is {accu}%.")
for i in range(len(prediction)):
  print(y_test[i],"          ",prediction[i])

Our model accuracy is 93%.
Iris-versicolor            Iris-versicolor
Iris-virginica            Iris-virginica
Iris-virginica            Iris-virginica
Iris-setosa            Iris-setosa
Iris-setosa            Iris-setosa
Iris-virginica            Iris-virginica
Iris-virginica            Iris-virginica
Iris-virginica            Iris-virginica
Iris-versicolor            Iris-versicolor
Iris-versicolor            Iris-virginica
Iris-virginica            Iris-virginica
Iris-setosa            Iris-setosa
Iris-setosa            Iris-setosa
Iris-versicolor            Iris-versicolor
Iris-setosa            Iris-setosa
Iris-setosa            Iris-setosa
Iris-setosa            Iris-setosa
Iris-versicolor            Iris-versicolor
Iris-setosa            Iris-setosa
Iris-versicolor            Iris-versicolor
Iris-setosa            Iris-setosa
Iris-versicolor            Iris-versicolor
Iris-versicolor            Iris-versicolor
Iris-versicolor            Iris-versicolor
Iris-setosa            Iri